### ISSUE TITLE
footer not stick to foot

### ISSUE THREAD

**Issue by ll911** [bcgov/gwa-ui#2]
**Describe the bug**
UI bug: footer not stick to foot

**To Reproduce**
any screen/page height longer than current browser window height.
in apikeys app, if create a long list apikeys, the key cards will float on top of footer

**Expected behavior**
footer should stick in foot 

**Screenshots**
apikey ui
![screen shot 2018-07-20 at 4](https://user-images.githubusercontent.com/11949273/43028814-f3b9a1c2-8c36-11e8-9e70-4c069a339bf0.png)
admin ui
<img width="1238" alt="screen shot 2018-07-20 at 4 07 30 pm" src="https://user-images.githubusercontent.com/11949273/43028830-091fa05c-8c37-11e8-80fd-6fd8e1c3d07e.png">

**Desktop (please complete the following information):**
 - OS: [MacOS]

**Comment by pauldaustin** [comment]
Missing parameter on my template that would have added scrolling. Fixed now

**Comment by ll911** [comment]
confirmed
