### ISSUE TITLE
favicon default in angular

### ISSUE THREAD

**Issue by ll911** [bcgov/gwa-ui#3]
**Describe the bug**
default favicon is set to use angular favicon

**To Reproduce**
see screen shot

**Expected behavior**
should be using https://data.gov.bc.ca/favicon.ico

**Screenshots**
<img width="144" alt="screen shot 2018-07-20 at 4 12 05 pm" src="https://user-images.githubusercontent.com/11949273/43028931-b6c0c1a0-8c37-11e8-9d89-89cf89884c9d.png">

**Desktop (please complete the following information):**
 - OS: [e.g. Mac]

**Comment by pauldaustin** [comment]
Updated favicon.ico for devkey and admin app

**Comment by ll911** [comment]
confirmed
